prompt PL/SQL Developer import file
prompt Created on quarta-feira, 20 de março de 2013 by Usuario
set feedback off
set define off
prompt Disabling triggers for USUARIO_ACESSO...
alter table USUARIO_ACESSO disable all triggers;
prompt Deleting USUARIO_ACESSO...
delete from USUARIO_ACESSO;
commit;
prompt Loading USUARIO_ACESSO...
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('137', 'FINANCEIRO -> CADASTROS -> FORMAS DE PAGAMENTO');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('257', 'CADASTROS -> FINANCEIRO -> FINANCEIRAS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('158', 'CADASTROS -> PRODUTOS -> TABELA DE PRECOS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('135', 'CADASTROS -> PRODUTOS -> PRODUTOS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('217', 'PEDIDOS -> PESQUISAR');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('277', 'CADASTROS -> FINANCEIRO -> TIPO DE PAGAMENTOS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('127', 'CADASTROS -> LOCALIDADE -> ESTADOS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('128', 'CADASTROS -> LOCALIDADE -> CIDADES');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('129', 'CADASTROS -> PESSOAS -> PESSOA');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('130', 'CADASTROS -> PESSOAS -> TIPO');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('131', 'CADASTROS -> CONTROLE DE USUARIOS -> CADASTRO DE USUARIOS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('133', 'CADASTROS -> CONTROLE DE USUARIO -> RESTRICOES');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('134', 'CADASTROS -> CONTROLE DE USUARIO -> CADASTRO DE GRUPOS DE USUARIOS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('177', 'PEDIDOS -> ORCAMENTOS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('125', 'CADASTROS -> UNIDADE DE MEDIDA');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('126', 'CADASTROS -> EMPRESAS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('258', 'CADASTROS -> FINANCEIRO -> PARAMETROS DAS FINANCEIRA');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('297', 'FINANCEIRO -> CARTOES -> PARAMETROS DAS TRANSAESCO');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('337', 'PEDIDO -> PEDIDOS A ENVIAR');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('338', 'PEDIDO -> PEDIDOS ENVIADOS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('197', 'CADASTROS -> PRODUTOS ->FICHA TECNICA');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('136', 'CADASTROS -> PRODUTOS -> GRUPO\SUB-GRUPO');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('132', 'CADASTROS -> CONTROLE DE USUARIO -> CADASTRO DE ACESSOS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('237', 'RELATORIOS -> VENDEDORES -> CARTEIRA DE CLIENTES');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('278', 'CADASTROS -> FINANCEIROS -> FORMAS DE PAGAMENTO');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('238', 'CADASTROS -> MARKETING -> PERGUNTAS');
insert into USUARIO_ACESSO (USUACECOD, USEACEDESC)
values ('317', 'CADASTROS -> CONFIGURACOES -> FILIAL');
commit;
prompt 27 records loaded
prompt Enabling triggers for USUARIO_ACESSO...
alter table USUARIO_ACESSO enable all triggers;
set feedback on
set define on
prompt Done.
